# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'iosapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # pod 'Firebase', '~> 2.1'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FirebaseUI/Facebook'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
  pod 'Cloudinary', '~2.0'
  # pod 'GeoFire', '~> 1.1'
  # Pods for iosapp

end
